#Hooray! You made it to the final day of Python! Do you have what it takes to be a Pythoneer?

#Lesson 3.0.0: Create files

In [1]:
#Use this block of code for notes
filename = 'first_file.txt'
with open(filename,'w') as f:
  f.write('hola!')

##Exercise 3.0.0: Create a file with gene names found in a List

In [11]:
#Use this block of code for notes
genes = ['CRTAM_HUMAN','CRTAM_MOUSE','CADM1_HUMAN']
for gene in genes:
  print(gene)

CRTAM_HUMAN
CRTAM_MOUSE
CADM1_HUMAN

In [14]:
#Kiara's way
with open('homologs.txt', 'w') as x:
  for name in genes:
    x.write(name + '\n')

In [20]:
# Kiara 2 example
with open('homologs.txt', 'w') as x:
  for name in genes:
    x.write('/t' + name + '/n')

with open('homologs.txt', 'w') as x:
  for name in genes:
    x.write('\t' + name + '\n')

In [22]:
#La profe's way
with open('homologs.txt', 'w') as x:
  for name in genes:
    x.write(name)
    x.write('\n')

#Lesson 3.1.1: Read in the lines of a file using a For Loop

In [23]:
#Use this block of code for notes
with open('homologs.txt','r') as x:
  for gene in x:
    print(gene.strip('\n'))

CRTAM_HUMAN
CRTAM_MOUSE
CADM1_HUMAN

In [ ]:
#Use strp(\n) to remove blank lines

#Lesson 3.1.2: Read in the lines of a file using a While Loop

In [ ]:
#Use this block of code for notes

#Lesson 3.2.0: Manipulate files the Panda way

##Lesson 3.2.1: Import the Panda Library

In [24]:
#Import library here

import pandas as pd

##Lesson 3.2.2: Read in a CSV file using a Panda Library

### Lesson 3.2.2a: Read in a CSV file with a header

In [38]:
#Use this block of code for notes
filename='crtam_with_header.csv'
table = pd.read_csv(filename,header=0,delimiter=',')
table

          Gene  length
0  CRTAM_HUMAN     393
1  CRTAM_MOUSE     781
2  CADMI_HUMAN     442

###Lesson 3.2.2b: Read in a CSV file with no header

In [42]:
#Use this block of code for notes
filename='crtam_without_header.csv'
table2 = pd.read_csv(filename,header=None,delimiter='\t')
table2

             0    1
0  CRTAM_HUMAN  393
1  CRTAM_MOUSE  781
2  CADMI_HUMAN  442

##Lesson 3.2.3: Create a DataFrame and export a new CSV file using Panda Library

###Lesson 3.2.3a: Create a Panda DataFrame from a single List

In [45]:
#Use this block of code for notes
genes=['CRTAM_HUMAN','CRTAM_MOUSE','CADMI_HUMAN']
pd.DataFrame(genes,columns=['name'])

          name
0  CRTAM_HUMAN
1  CRTAM_MOUSE
2  CADMI_HUMAN

###Lesson 3.2.3b: Create a Panda DataFrame from multiple Lists

In [50]:
#Use this block of code for notes
crtam_human = ['CRTAM',393,'human']
crtam_mouse = ['CRTAM',393,'mouse']
cadm1_human = ['CADM1',442,'human']

pd.DataFrame([crtam_human,crtam_mouse,cadm1_human],
             columns=['gene','length','organism'])

    gene  length organism
0  CRTAM     393    human
1  CRTAM     393    mouse
2  CADM1     442    human

In [63]:
gene_dictionary = {'CRTAM_HUMAN':{'length':393,'organism':'human'},
                   'CRTAM_MOUSE':{'length':781,'organism':'mouse'},
                   'CADM1_HUMAN':{'length':442,'organism':'human'}}

df = pd.DataFrame(gene_dictionary)
df = df.T
df = df.reset_index()
df = df.rename(columns={'index':'gene'})
df

df2 = pd.DataFrame(gene_dictionary).T.reset_index().rename(columns={'index':'gene'})
df2

          gene length organism
0  CRTAM_HUMAN    393    human
1  CRTAM_MOUSE    781    mouse
2  CADM1_HUMAN    442    human

In [67]:
df2.to_csv('gene_dictionary_with_tab.csv',sep='\t')
df2.to_csv('gene_dictionary_with_comma.csv',sep=',')

###Lesson 3.2.3c: Create a Panda DataFrame from a Nested Dictionary

In [ ]:
#Use this block of code for notes

##Lesson 3.2.4: Export a Panda DataFrame as a CSV File

In [ ]:
#Use this block of code for notes

#Proficiency Assessment

##create .faa file (this section of code is not for the class)

In [ ]:
with open('crtam.faa', 'w') as f:
    f.write('>CRTAM_HUMAN')
    f.write('\n')
    f.write('MWWRVLSLLAWFPLQEASLTNHTETITVEEGQTLTLKCVTSLRKNSSLQWLTPSGFTIFLNEYPALKNSKYQLLHHSANQLSITVPNVTLQDEGVYKCLHYSDSVSTKEVKVIVLATPFKPILEASVIRKQNGEEHVVLMCSTMRSKPPPQITWLLGNSMEVSGGTLHEFETDGKKCNTTSTLIIHTYGKNSTVDCIIRHRGLQGRKLVAPFRFEDLVTDEETASDALERNSLSSQDPQQPTSTVSVTEDSSTSEIDKEEKEQTTQDPDLTTEANPQYLGLARKKSGILLLTLVSFLIFILFIIVQLFIMKLRKAHVIWKRENEVSEHTLESYRSRSNNEETSSEEKNGQSSHPMRCMNYITKLYSEAKTKRKENVQHSKLEEKHIQVPESIV')
    f.write('\n')
    f.write('>CRTAM_MOUSE')
    f.write('\n')
    f.write('MWWGVLSLLFWVPVQAAFLKMETVTVEEGQTLTLTCVTSQTKNVSLQWLAPSGFTIFLNQHPALKSSKYQLLHHSATQLSISVSNVTLREEGVYTCLHYGSSVKTKQVRVTVLVTPFQPTVEALVLRRQNGEKSVVLKCSTERSKPPPQITWLLGEGLEIYGELHHEFEADGKICNTSSTLIARAYGKNSTVHCIIQHEGLHGRKLVAPFQFEDLVADQETTSDAPEQSSLSSQALQQPTSTVSMMENSSIPETDKEEKEHATQDPGLSTASAQHTGLARRKSGILLLTLVSFLIFILFIIVQLFIMKLRKAHVVWKKESEISEQALESYRSRSNNEETSSQENSSQAPQSKRCMNYITQLYSGAKTKKSAQHWKLGGKHSRVPESIV')
    f.write('\n')
    f.write('>CADM1_HUMAN')
    f.write('\n')
    f.write('MASVVLPSGSQCAAAAAAAAPPGLRLRLLLLLFSAAALIPTGDGQNLFTKDVTVIEGEVATISCQVNKSDDSVIQLLNPNRQTIYFRDFRPLKDSRFQLLNFSSSELKVSLTNVSISDEGRYFCQLYTDPPQESYTTITVLVPPRNLMIDIQRDTAVEGEEIEVNCTAMASKPATTIRWFKGNTELKGKSEVEEWSDMYTVTSQLMLKVHKEDDGVPVICQVEHPAVTGNLQTQRYLEVQYKPQVHIQMTYPLQGLTREGDALELTCEAIGKPQPVMVTWVRVDDEMPQHAVLSGPNLFINNLNKTDNGTYRCEASNIVGKAHSDYMLYVYDPPTTIPPPTTTTTTTTTTTTTILTIITDSRAGEEGSIRAVDHAVIGGVVAVVVFAMLCLLIILGRYFARHKGTYFTHEAKGADDAADADTAIINAEGGQNNSEEKKEYFI')

In [ ]:
with open('crtam_with_header.csv', 'w') as f:
    f.write('gene,length')
    f.write('\n')
    f.write('CRTAM_HUMAN')
    f.write(',')
    f.write('393')
    f.write('\n')
    f.write('CRTAM_MOUSE')
    f.write(',')
    f.write('781')
    f.write('\n')
    f.write('CADM1_HUMAN')
    f.write(',')
    f.write('442')

In [ ]:
with open('crtam_without_header.csv', 'w') as f:
    f.write('CRTAM_HUMAN')
    f.write('\t')
    f.write('393')
    f.write('\n')
    f.write('CRTAM_MOUSE')
    f.write('\t')
    f.write('781')
    f.write('\n')
    f.write('CADM1_HUMAN')
    f.write('\t')
    f.write('442')

##for loop through the line of a file

In [ ]:
fasta_file = open('crtam.faa','r')
for fasta_line in fasta_file:
  print(fasta_line)
fasta_file.close()

>CRTAM_HUMAN

MWWRVLSLLAWFPLQEASLTNHTETITVEEGQTLTLKCVTSLRKNSSLQWLTPSGFTIFLNEYPALKNSKYQLLHHSANQLSITVPNVTLQDEGVYKCLHYSDSVSTKEVKVIVLATPFKPILEASVIRKQNGEEHVVLMCSTMRSKPPPQITWLLGNSMEVSGGTLHEFETDGKKCNTTSTLIIHTYGKNSTVDCIIRHRGLQGRKLVAPFRFEDLVTDEETASDALERNSLSSQDPQQPTSTVSVTEDSSTSEIDKEEKEQTTQDPDLTTEANPQYLGLARKKSGILLLTLVSFLIFILFIIVQLFIMKLRKAHVIWKRENEVSEHTLESYRSRSNNEETSSEEKNGQSSHPMRCMNYITKLYSEAKTKRKENVQHSKLEEKHIQVPESIV

>CRTAM_MOUSE

MWWGVLSLLFWVPVQAAFLKMETVTVEEGQTLTLTCVTSQTKNVSLQWLAPSGFTIFLNQHPALKSSKYQLLHHSATQLSISVSNVTLREEGVYTCLHYGSSVKTKQVRVTVLVTPFQPTVEALVLRRQNGEKSVVLKCSTERSKPPPQITWLLGEGLEIYGELHHEFEADGKICNTSSTLIARAYGKNSTVHCIIQHEGLHGRKLVAPFQFEDLVADQETTSDAPEQSSLSSQALQQPTSTVSMMENSSIPETDKEEKEHATQDPGLSTASAQHTGLARRKSGILLLTLVSFLIFILFIIVQLFIMKLRKAHVVWKKESEISEQALESYRSRSNNEETSSQENSSQAPQSKRCMNYITQLYSGAKTKKSAQHWKLGGKHSRVPESIV

>CADM1_HUMAN

MASVVLPSGSQCAAAAAAAAPPGLRLRLLLLLFSAAALIPTGDGQNLFTKDVTVIEGEVATISCQVNKSDDSVIQLLNPNRQTIYFRDFRPLKDSRFQLLNFSSSELKVSLTNVSISDEGRYFCQLYTDPPQESYTTITVLVPPRNLMIDIQRDTAVEGEEIEVNCTAMASKPATTIRWFKGNTELKGKSEVEEWSDMYTVTSQLMLKVHKEDDGVPVICQVEHPAVTGNLQTQRYLEVQYKPQVHIQMTYPLQGLTREGDALELTCEAIGKPQPVMVTWVRVDDEMPQHAVLSGPNLFINNLNKTDNGTYRCEASNIVGKAHSDYMLYVYDPPTTIPPPTTTTTTTTTTTTTILTIITDSRAGEEGSIRAVDHAVIGGVVAVVVFAMLCLLIILGRYFARHKGTYFTHEAKGADDAADADTAIINAEGGQNNSEEKKEYFI

##while loop through the line of a file

In [ ]:
fasta_file = open('crtam.faa','r')
fasta_lines = fasta_file.readline()
while fasta_lines:
  print(fasta_lines)
  fasta_lines = fasta_file.readline()
fasta_file.close()

>CRTAM_HUMAN

MWWRVLSLLAWFPLQEASLTNHTETITVEEGQTLTLKCVTSLRKNSSLQWLTPSGFTIFLNEYPALKNSKYQLLHHSANQLSITVPNVTLQDEGVYKCLHYSDSVSTKEVKVIVLATPFKPILEASVIRKQNGEEHVVLMCSTMRSKPPPQITWLLGNSMEVSGGTLHEFETDGKKCNTTSTLIIHTYGKNSTVDCIIRHRGLQGRKLVAPFRFEDLVTDEETASDALERNSLSSQDPQQPTSTVSVTEDSSTSEIDKEEKEQTTQDPDLTTEANPQYLGLARKKSGILLLTLVSFLIFILFIIVQLFIMKLRKAHVIWKRENEVSEHTLESYRSRSNNEETSSEEKNGQSSHPMRCMNYITKLYSEAKTKRKENVQHSKLEEKHIQVPESIV

>CRTAM_MOUSE

MWWGVLSLLFWVPVQAAFLKMETVTVEEGQTLTLTCVTSQTKNVSLQWLAPSGFTIFLNQHPALKSSKYQLLHHSATQLSISVSNVTLREEGVYTCLHYGSSVKTKQVRVTVLVTPFQPTVEALVLRRQNGEKSVVLKCSTERSKPPPQITWLLGEGLEIYGELHHEFEADGKICNTSSTLIARAYGKNSTVHCIIQHEGLHGRKLVAPFQFEDLVADQETTSDAPEQSSLSSQALQQPTSTVSMMENSSIPETDKEEKEHATQDPGLSTASAQHTGLARRKSGILLLTLVSFLIFILFIIVQLFIMKLRKAHVVWKKESEISEQALESYRSRSNNEETSSQENSSQAPQSKRCMNYITQLYSGAKTKKSAQHWKLGGKHSRVPESIV

>CADM1_HUMAN

MASVVLPSGSQCAAAAAAAAPPGLRLRLLLLLFSAAALIPTGDGQNLFTKDVTVIEGEVATISCQVNKSDDSVIQLLNPNRQTIYFRDFRPLKDSRFQLLNFSSSELKVSLTNVSISDEGRYFCQLYTDPPQESYTTITVLVPPRNLMIDIQRDTAVEGEEIEVNCTAMASKPATTIRWFKGNTELKGKSEVEEWSDMYTVTSQLMLKVHKEDDGVPVICQVEHPAVTGNLQTQRYLEVQYKPQVHIQMTYPLQGLTREGDALELTCEAIGKPQPVMVTWVRVDDEMPQHAVLSGPNLFINNLNKTDNGTYRCEASNIVGKAHSDYMLYVYDPPTTIPPPTTTTTTTTTTTTTILTIITDSRAGEEGSIRAVDHAVIGGVVAVVVFAMLCLLIILGRYFARHKGTYFTHEAKGADDAADADTAIINAEGGQNNSEEKKEYFI